#!/usr/bin/env ruby
require 'uri'
require 'mechanize'

TO_CRAWL = %w{
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/entertainers/21-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/entertainers/21-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ct-connecticut/hartford/travel-agents/23-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-services/20-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/entertainers/21-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/party-supplies/22-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/fl-florida/jacksonville/travel-agents/23-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-services/20-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/entertainers/21-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/party-supplies/22-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/fl-florida/panama-city/travel-agents/23-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-services/20-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/entertainers/21-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/party-supplies/22-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/hi-hawaii/honolulu/travel-agents/23-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-services/20-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/entertainers/21-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/party-supplies/22-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/mi-michigan/detroit/travel-agents/23-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-services/20-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/entertainers/21-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/party-supplies/22-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/mn-minnesota/minneapolis/travel-agents/23-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-services/20-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/entertainers/21-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/party-supplies/22-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/charlotte/travel-agents/23-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-services/20-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/entertainers/21-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/party-supplies/22-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/nc-north-carolina/raleigh/travel-agents/23-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-services/20-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/entertainers/21-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/party-supplies/22-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/oh-ohio/cleveland/travel-agents/23-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-services/20-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/entertainers/21-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/party-supplies/22-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/on-ontario/toronto/travel-agents/23-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-services/20-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/entertainers/21-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/party-supplies/22-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/or-oregon/portland/travel-agents/23-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-services/20-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/entertainers/21-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/party-supplies/22-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/lancaster/travel-agents/23-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-services/20-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/entertainers/21-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/party-supplies/22-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/pittsburgh/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/entertainers/21-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ri-rhode-island/providence/travel-agents/23-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-services/20-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/entertainers/21-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/party-supplies/22-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/tn-tennessee/nashville/travel-agents/23-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-services/20-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/entertainers/21-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/party-supplies/22-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/va-virginia/hampton/travel-agents/23-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-services/20-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/entertainers/21-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/party-supplies/22-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/wi-wisconsin/milwaukee/travel-agents/23-vendors.html
}

@agent = Mechanize.new
@agent.user_agent = 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
@agent.read_timeout = 5
@agent.keep_alive = false

start = Time.now
TO_CRAWL.each do |page|
  @agent.get(page)
  puts "Crawled #{page}"
end

puts "Done in #{(Time.now - start).round(4)}s"