#!/usr/bin/env ruby
require 'uri'
require 'mechanize'

TO_CRAWL = %w{
http://www.weddingwire.com/wedding-forums
http://www.weddingwire.com/wedding-photos/dresses
http://www.weddingwire.com/wedding-photos/bridesmaids
http://www.weddingwire.com/wedding-dresses/ideas
http://www.weddingwire.com/wedding-photos
http://www.weddingwire.com/wedding-photos/real-weddings
http://www.weddingwire.com/wedding-photos/jewelry
http://www.weddingwire.com/wedding-photos/dresses
http://www.weddingwire.com/wedding-photos/invitations
http://www.weddingwire.com/wedding-photos/cakes
http://www.weddingwire.com/wedding-photos/flowers
http://www.weddingwire.com/wedding-photos/hair
http://www.weddingwire.com/wedding-photos/favors
http://www.weddingwire.com/wedding-songs/first-dance-music
http://www.weddingwire.com/wedding-registry
http://www.weddingwire.com/honeymoons/caribbean
http://www.weddingwire.com/honeymoons/north-america
http://www.weddingwire.com/honeymoons/mexico
http://www.weddingwire.com/honeymoons/europe
http://www.weddingwire.com/honeymoons/hawaii
http://www.weddingwire.com/honeymoons/south-pacific
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/entertainers/21-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ga-georgia/atlanta/travel-agents/23-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-services/20-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/entertainers/21-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/party-supplies/22-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/md-maryland/baltimore/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/entertainers/21-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ma-massachusetts/boston/travel-agents/23-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-services/20-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/entertainers/21-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/party-supplies/22-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/il-illinois/chicago/travel-agents/23-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-services/20-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/entertainers/21-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/party-supplies/22-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/tx-texas/dallas/travel-agents/23-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-services/20-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/entertainers/21-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/party-supplies/22-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/co-colorado/denver/travel-agents/23-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-services/20-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/entertainers/21-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/party-supplies/22-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/tx-texas/houston/travel-agents/23-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-services/20-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/entertainers/21-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/party-supplies/22-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/nv-nevada/las-vegas/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/entertainers/21-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ca-california/los-angeles/travel-agents/23-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-services/20-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/entertainers/21-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/party-supplies/22-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/fl-florida/miami/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/entertainers/21-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ny-new-york/new-york/travel-agents/23-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-services/20-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/entertainers/21-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/party-supplies/22-vendors.html
}

@agent = Mechanize.new
@agent.user_agent = 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
@agent.read_timeout = 5
@agent.keep_alive = false

start = Time.now
TO_CRAWL.each do |page|
  @agent.get(page)
  puts "Crawled #{page}"
end

puts "Done in #{(Time.now - start).round(4)}s"

