#!/usr/bin/env ruby
require 'uri'
require 'mechanize'

TO_CRAWL = %w{
http://www.weddingwire.com/c/fl-florida/orlando/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/fl-florida/orlando/travel-agents/23-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-services/20-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/entertainers/21-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/party-supplies/22-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/pa-pennsylvania/philadelphia/travel-agents/23-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-services/20-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/entertainers/21-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/party-supplies/22-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/az-arizona/phoenix/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/entertainers/21-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ca-california/san-francisco/travel-agents/23-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-services/20-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/entertainers/21-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/party-supplies/22-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/wa-washington/seattle/travel-agents/23-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-services/20-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/entertainers/21-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/party-supplies/22-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/dc-district-of-columbia/washington/travel-agents/23-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-services/20-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/entertainers/21-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/party-supplies/22-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/fl-florida/tampa/travel-agents/23-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-services/20-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/entertainers/21-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/party-supplies/22-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/dover/travel-agents/23-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-services/20-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/entertainers/21-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/party-supplies/22-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/nj-new-jersey/burlington/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/entertainers/21-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ca-california/irvine/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/entertainers/21-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ny-new-york/freeport/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/entertainers/21-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ct-connecticut/westport/travel-agents/23-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-services/20-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/entertainers/21-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/party-supplies/22-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/va-virginia/richmond/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/entertainers/21-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ca-california/sacramento/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-services/20-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-videographers/14-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-cakes/2-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-planners/15-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-ceremony-music/4-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-djs/7-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-dresses/17-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/entertainers/21-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-event-rentals/12-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-favors/5-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-florists/8-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-invitations/18-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-jewelers/19-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/lighting-decor/24-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-officiants/9-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/party-supplies/22-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-photographers/10-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/rehearsal-dinner-locations/25-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/wedding-limos/13-vendors.html
http://www.weddingwire.com/c/ca-california/san-diego/travel-agents/23-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-bands/1-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-beauty-health/16-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-caterers/3-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-venues/11-vendors.html
http://www.weddingwire.com/c/ca-california/santa-barbara/wedding-services/20-vendors.html
}

@agent = Mechanize.new
@agent.user_agent = 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
@agent.read_timeout = 5
@agent.keep_alive = false

start = Time.now
TO_CRAWL.each do |page|
  @agent.get(page)
  puts "Crawled #{page}"
end

puts "Done in #{(Time.now - start).round(4)}s"

